name: Docs

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      ref:
        description: >-
          The ref to checkout and use to create docs
        type: string
        default: ""
      push:
        description: >-
          Push the documentation to the remote branch
        type: boolean
        default: true
      type:
        description: >-
          MkDocs or zensical
        type: string
        default: zensical

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/configure-pages@v6

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to push to the documentation branch
          ref: ${{ inputs.ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Sync dependencies
        if: inputs.type == 'zensical'
        run: |
          uv sync --no-dev --group docs
          uv run zensical build --clean

      - name: Build documentation
        if: inputs.type == 'mkdocs'
        run: |
          uv sync --no-dev --group mkdocs
          uv run mkdocs build --clean

      - uses: actions/upload-pages-artifact@v5
        if: ${{ inputs.push }}
        with:
          path: site

      - uses: actions/deploy-pages@v5
        if: ${{ inputs.push }}
        id: deployment
